### ISSUE TITLE
Final project deliverables checklist

### ISSUE THREAD

**Issue by TechSolomon** [andrewsng/assistive-technology#17]
- [x] Project Code 
    - [x] Fork GitHub repository
    - [x] Source on USB
- [x] Documentation via [wiki](https://github.com/andrewsng/assistive-technology/wiki)
    - [x] Code commenting
- [x] Windows compatible (.exe) file
- [x] [Architecture diagram](https://github.com/andrewsng/assistive-technology#architecture-diagram)
    - [x] Hardware handoff & system compatibility
- [x] Twin setups [AK + OH]
    - [x] Arduino or similar type

**Comment by TechSolomon** [comment]
Explore GitHub Actions as way to manage released (https://github.com/andrewsng/assistive-technology/releases/new) executable files & best practices for version numbers (#19).

**Comment by TechSolomon** [comment]
Wiki should be cloned and added to the `/docs` directory to preserve information post-fork.
